[versions]
python = "3.10.2"

[tasks.setup]
name = "setup"
command = "pip3 install -r requirements.txt"

[tasks.version]
command = "python --version"

[tasks.run]
command = "python app.py"
default = true

[tasks.test]
command = "pytest"

[tasks.coverage]
command = "coverage run -m pytest && coverage report -m"

[tasks.lint]
command = "flake8 ."

[tasks.format]
command = "black ."

[tasks.create-env]
command = "python -m venv env"

[tasks.activate-env]
command = "source env/bin/activate"

[tasks.migrate]
command = "python manage.py migrate"
